### ISSUE TITLE
代码为什么不放在git而是网盘 不方便管理哦

### ISSUE THREAD

**Issue by MoYu513** [Honlan/DeepInterests#1]

**Comment by Honlan** [comment]
关于代码如何发布这个问题其实我反复考虑过。代码文本在知乎等地方都能找到，如果仅仅上传代码文件到git上，没有对应路径下的资源、图片、文本、数据等，即便有了代码也跑不了。所以为了方便大家使用，才决定把所有内容都放到网盘上，下载下来之后就可以跑代码

**Comment by ouckate** [comment]
的确是，放在一起方便了学习和刊读

**Comment by zzzzjjjxxx** [comment]
> 关于代码如何发布这个问题其实我反复考虑过。代码文本在知乎等地方都能找到，如果仅仅上传代码文件到git上，没有对应路径下的资源、图片、文本、数据等，即便有了代码也跑不了。所以为了方便大家使用，才决定把所有内容都放到网盘上，下载下来之后就可以跑代码

那请问一下博主，要怎么才能把代码运行起来
